image: composer:2.0

definitions:
  caches:
    composer: /root/.composer/cache
    node: /root/.npm

pipelines:
  branches:
    dev:
      - parallel:
        - step:
            name: PHP Code Smells
            script:
              - composer install --prefer-dist --no-interaction --no-scripts
              - ./vendor/bin/phpcs --standard=PSR12 app/
        - step:
            name: Laravel Pint Format
            script:
              - composer install --prefer-dist --no-interaction --no-scripts
              - ./vendor/bin/pint --test
        - step:
            name: Composer Update
            script:
              - composer install --prefer-dist --no-interaction --no-scripts
              - composer update --dry-run
      - step:
          name: Test Laravel
          script:
            - composer install
            - ./vendor/bin/phpunit test
      - step:
          name: Lint Laravel
          script:
            - composer install
            - ./vendor/bin/phplint . --exclude=vendor
