#!/bin/bash
# Script to create Google OAuth client for oceansgaming-staging

echo "Creating OAuth client for project: tf-driftwood-dev"
echo "Environment: staging"
echo ""
echo "Please create an OAuth client in Google Cloud Console with these settings:"
echo ""
echo "Project: tf-driftwood-dev"
echo "Application Type: Web application"
echo "Name: oceansgaming-staging-web-client"
echo ""
echo "Authorized JavaScript origins:"
echo "- http://localhost:8000"
echo "- https://oceansgaming.gg"
echo "- https://driftwood.gg"
echo ""
echo "Authorized redirect URIs:"
echo "- http://localhost:8000/auth/google/callback"
echo "- https://driftwood.gg/auth/google/callback"
echo "- https://oceansgaming.gg/auth/google/callback"
echo ""
echo "After creating the OAuth client:"
echo "1. Copy the Client ID and Client Secret"
echo "2. Update your .env file with the credentials:"
echo "   GOOGLE_CLIENT_ID=your_client_id_here"
echo "   GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo ""
echo "Google Cloud Console URL:"
echo "https://console.cloud.google.com/apis/credentials?project=tf-driftwood-dev"
