<?php

return [
    'mappingEventState' => [
        'ERROR' => [
            'buttonBackgroundColor' => '#EF4444',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'PENDING' => [
            'buttonBackgroundColor' => '#EF4444',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'UPCOMING' => [
            'buttonBackgroundColor' => '#43A4D7',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'LIVE' => [
            'buttonBackgroundColor' => '#43A4D7',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'SCHEDULED' => [
            'buttonBackgroundColor' => '#43A4D7',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'ONGOING' => [
            'buttonBackgroundColor' => '#FFFBFB',
            'buttonTextColor' => 'black',
            'borderColor' => 'black',
        ],
        'DRAFT' => [
            'buttonBackgroundColor' => '#8CCD39',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'PREVIEW' => [
            'buttonBackgroundColor' => '#8CCD39',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
        'ENDED' => [
            'buttonBackgroundColor' => '#A6A6A6',
            'buttonTextColor' => 'white',
            'borderColor' => 'transparent',
        ],
    ],
    'eWalletLogos' => [
        [
            'src' => 'boost-pay-ewallet-logo.png',
            'name' => 'Boost Pay',
            'width' => 60,
            'height' => 60,
            'cover' => false,
        ],
        [
            'src' => 'grab-pay-ewallet-logo.webp',
            'name' => 'Grab Pay',
            'width' => 60,
            'height' => 60,
            'cover' => true,
        ],
        [
            'src' => 'mae-ewallet-logo.png',
            'name' => 'MAE',
            'width' => 60,
            'height' => 60,
            'cover' => true,
        ],
        [
            'src' => 'shopee-ewallet-logo.png',
            'name' => 'Shopee Pay',
            'width' => 60,
            'height' => 60,
            'cover' => true,
        ],
        [
            'src' => 'touch-n-go-ewallet-logo.png',
            'name' => 'TouchNGo Pay',
            'width' => 60,
            'height' => 60,
            'cover' => true,
        ],
    ],
    'otherEWalletLogos' => [
        [
            'src' => 'apple-ewallet-logo.png',
            'name' => 'Apple Pay',
            'width' => 60,
            'height' => 60,
            'cover' => false,
        ],
        [
            'src' => 'google-pay-ewallet-logo.png',
            'name' => 'Google Pay',
            'width' => 60,
            'height' => 60,
            'cover' => true,
        ],
        [
            'src' => 'paypal-ewallet-logo.png',
            'name' => 'Paypal',
            'width' => 60,
            'height' => 60,
            'cover' => false,
        ],
    ],
    'bankLogos' => [
        [
            'src' => 'affin-bank-logo.jpeg',
            'name' => 'Affin Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'alliance-bank-logo.png',
            'name' => 'Alliance Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'am-bank-logo.jpg',
            'name' => 'AmBank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'islam-bank-logo.jpg',
            'name' => 'Bank Islam',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'rakyat-bank-logo.png',
            'name' => 'Rakyat Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'bsn-bank-logo.png',
            'name' => 'BSN Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'cimb-bank-logo.png',
            'name' => 'CIMB Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'citi-bank-logo.avif',
            'name' => 'Citibank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'hong-leong-bank-logo.png',
            'name' => 'Hong Leong Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'hsbc-bank-logo.png',
            'name' => 'HSBC Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'may-bank-logo.png',
            'name' => 'Maybank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],

        [
            'src' => 'ocbc-bank-logo.png',
            'name' => 'OCBC Bank',
            'width' => 80,
            'height' => 48,
            'cover' => false,
        ],
        [
            'src' => 'public-bank-logo.png',
            'name' => 'Public Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'rhb-bank-logo.png',
            'name' => 'RHB Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],

        [
            'src' => 'standard-chartered-bank-logo.jpg',
            'name' => 'Standard Chartered Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
        [
            'src' => 'uob-bank-logo.png',
            'name' => 'UOB Bank',
            'width' => 80,
            'height' => 48,
            'cover' => true,
        ],
    ],
];
